### ISSUE TITLE
Fix Console Errors

### ISSUE THREAD

**Issue by d-schaffer** [d-schaffer/buy-me-a-beer-button#3]
[Vue warn]: Property or method "submit" is not defined on the instance but referenced during render.
....

`[Vue warn]: Invalid handler for event "submit": got undefined

found in

---> <DonateButton> at src/components/DonateButton.vue
       <App> at src/App.vue
         <Root>`

**Comment by sadn1ck** [comment]
Can I work on this? Component sources are to me but I'll try my best.

**Comment by d-schaffer** [comment]
sure :) say if you need help :)

**Comment by sadn1ck** [comment]
Okay so I had a look at the source, and the issue arises because there's a @submit event but that isn't handled by any function. Does the button need the @submit? It already is a link.
